[package]
name = "r2r_regular_markers"
version = "0.0.1"
authors = ["Endre Erős <endre.eros@chalmersindustriteknik.se>"]
edition = "2021"
autotests = true


[profile.colcon]
inherits = "release"

[dependencies]
r2r = "0.9.0"
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }